---
booktitle: Proceedings of ICML Workshop on Unsupervised and Transfer Learning
publisher: JMLR Workshop and Conference Proceedings
volume: 27
year: '2011'
shortname: UTLW
start: 2011-07-02
end: 2011-07-02
published: 2012-06-27
sections:
- name: intro
  title: Introduction
- name: theory
  title: Fundamentals and theory
- name: challenge
  title: Challenge contributions
- name: default
  title: Advances in transfer learning
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: UTLW-2011
month: 0
cycles: false
editor:
- given: Isabelle
  family: Guyon
- given: Gideon
  family: Dror
- given: Vincent
  family: Lemaire
- given: Graham
  family: Taylor
- given: Daniel
  family: Silver
title: Proceedings of Machine Learning Research
description: |
  Proceedings of ICML Workshop on Unsupervised and Transfer Learning
    Held in Bellevue, Washington, USA on 02 July 2011

  Published as Volume 27 by the Proceedings of Machine Learning Research on 27 June 2012.

  Volume Edited by:
    Isabelle Guyon
    Gideon Dror
    Vincent Lemaire
    Graham Taylor
    Daniel Silver

  Series Editors:
    Neil D. Lawrence
date_str: 02 Jul
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v27"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v27
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Proceedings of ICML Workshop on Unsupervised and Transfer Learning
  url: 
  location: Bellevue, Washington, USA
  dates:
  - 2011-07-02
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
